### PR TITLE
OPENEUROPA-336: Update composer cmd to use dev-master version.

### PR DESCRIPTION
**Pull request by aritomelo**
Update composer cmd to use dev-master version, as the "drupal-module-template" project still not been released.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Instead of documenting a workaround, why not simply make a first 0.1.0 release?

**Comment by drupol** [comment]
Rebasing against master and fixing typo in the commit log message.

**Comment by drupol** [comment]
@richardcanoe What should we do with this issue ?

**Comment by dxvargas** [comment]
Release 0.1.0 is now available, no need to update README anymore.

**Pull request closed without merging**
